### ISSUE TITLE
Undefined variable: options

### ISSUE THREAD

**Issue by cesagonchu** [XoopsModules25x/xoopspoll#11]
When I create a poll into newbb and forget to enter the options here (modules/newbb/polls.php?op=add&topic_id=2):

![image](https://cloud.githubusercontent.com/assets/4613970/9699433/fdf95158-53e2-11e5-9df0-282f9c6ee69a.png)

I get this error (modules/newbb/viewtopic.php?topic_id=2):

Notice: Undefined variable: options in file /modules/xoopspoll/class/renderer.php line 139

**Comment by mambax7** [comment]
Please check this fix:
https://github.com/mambax7/xoopspoll/commit/129c82b2cf3a8390241e4999ef5976a1ac01ac20

**Comment by cesagonchu** [comment]
Now the options are no longer displayed.
Before:
![image](https://cloud.githubusercontent.com/assets/4613970/9706044/5b28c4b6-54d9-11e5-85e1-7a37d674538f.png)

After:
![image](https://cloud.githubusercontent.com/assets/4613970/9706047/683249e8-54d9-11e5-94cc-cf0103e8d5ce.png)

No errors with debug mode.

**Comment by mambax7** [comment]
Oops! Sorry for that. I'll fix it later today....

**Comment by cesagonchu** [comment]
No problem and thanks ;-)

**Comment by mambax7** [comment]
Check the fix: https://github.com/mambax7/xoopspoll/commit/61be2a6dde822aa919a727bb93b34263e96fc29b

**Comment by cesagonchu** [comment]
Fixed, but when I want to vote I get this message:

There was a problem registering your vote. Please try again.

**Comment by mambax7** [comment]
Arrgh!!!!  Try this NewBB fix: https://github.com/mambax7/newbb/commit/c00e42707052fffefbf072d9416538d7c96a8940

**Comment by cesagonchu** [comment]
It's ok now I can vote :-)
