### ISSUE TITLE
xoopspoll and newbb

### ISSUE THREAD

**Issue by ggoffy** [XoopsModules25x/xoopspoll#19]
Error: Class 'XoopsModules/Xoopspoll/Constants' not found in Datei /modules/xoopspoll/class/PollHandler.php Zeile 86

both modules are latest version from Github

Xoops 2.5.11
PHP 7.3

**Comment by mambax7** [comment]
But where does it happen? How could I reproduce it? 
Try to add on top of PollHandler.php:

`use XoopsModules\Xoopspoll\Constants;`

But it shouldn't really matter, because they are both in the same namespace. 

If you let me know how I could reproduce it, I'll try to look into more details

**Comment by masel67** [comment]
Check register file class/Constants.php. May be constants.php

**Comment by zyspec** [comment]
It appears there are two (2) constants class files (constants.php and Constants.php). Delete the constants.php (lower case 'C') file. This could be the problem if you're using an operating system that ignores case for file names...


    On Wednesday, December 9, 2020, 09:39:57 AM CST, Alexey <notifications@github.com> wrote:  
 
 


Check register file class/Constants.php. May be constants.php

**Comment by cesagonchu** [comment]
So why not delete this duplicate file?
https://github.com/mambax7/xoopspoll/blob/master/class/constants.php

**Comment by mambax7** [comment]
Done!
