### ISSUE TITLE
Undefined constant _AM_XOOPSPOLL_CREATENEWPOLL

### ISSUE THREAD

**Issue by cesagonchu** [XoopsModules25x/xoopspoll#21]
When I want to create a poll from a Newbb forum topic (modules/newbb/polls.php?op=add&topic_id=1) I get this error:

> Error : Error: Undefined constant '_AM_XOOPSPOLL_CREATENEWPOLL'

I tested on a brand new installation of Xoops.
___

My config:

PHP  7.4.9
MYSQL 5.7.33-0ubuntu0.16.04.1
XOOPS 2.5.11-Beta2
XOOPS Polls 2.01 Beta 1
Newbb 5.01 Beta 4

**Comment by mambax7** [comment]
There were some issues between NewBB and XoopsPoll, that need to be fixed. 

In the meantime, you can try my fork and see if it's better. I've made some updates, but it's still work in progress, so there might be plenty of old and new bugs. But I would appreciate some testing!  Thanks!

**Comment by cesagonchu** [comment]
With your changes, when I go to the administration homepage of the XoopsPoll module (modules/xoopspoll/admin/index.php), I get this error:

> Error : Error: Call to undefined function loadAdminConfig()

**Comment by mambax7** [comment]
Thank you! I'll look into it this weekend.

**Comment by mambax7** [comment]
The missing loadAdminConfig() has been now fixed

**Comment by cesagonchu** [comment]
The module is now functional, thank you!
However, when I create a poll in a forum, is it normal that the poll is not displayed in the forum topic, but only in XoopsPoll?

**Comment by cesagonchu** [comment]
Finally, the poll is not created, see details here:
https://www.frxoops.org/modules/newbb/viewtopic.php?post_id=242531#forumpost242531

**Comment by mambax7** [comment]
Please check:
https://github.com/mambax7/xoopspoll
https://github.com/mambax7/newbb

This is still work in progress (bugs are still possible), but it seems to be working here, i.e. the poll is created

**Comment by cesagonchu** [comment]
Thanks!
Creating polls on the forums works now but please take a look here:
https://github.com/XoopsModules25x/xoopspoll/issues/22#issue-862991484
