### ISSUE TITLE
Expiration date modification

### ISSUE THREAD

**Issue by slider84** [XoopsModules25x/xoopspoll#5]
It is not possible to modify the expiration date of an existing poll (in the admin panel)

**Comment by slider84** [comment]
same issue when creating a new poll. The end date is always +10 days from the begin date.

**Comment by slider84** [comment]
French translation problem:
In the admin it's written that date must be 20/07/2015 format but we can change date if she is with english separator (20-07-2015 12:43)

**Comment by mambax7** [comment]
I have no problems changing the date using the pop-up calendar? Are you changing the date manually by typing the date, or are you using the pop-calendar? 
If manually, ignore the "suggested" format, and use the format that you have given by XoopsPoll. For example I have the date as "2015/08/15 00:00" and not   "yyyy-mm-dd hh:mm". I think, the statement about the format was more about making sure that the date starts with "2015", and not about the date separators.

**Comment by slider84** [comment]
I don't have popup calendar...
i confirm: it's a date separator issue not a date format. Have a look to the beta2 french translation:
define('_AM_XOOPSPOLL_DTP_DATEFORMAT', "dd-mm-yy")

**Comment by mambax7** [comment]
Can you change it in the French translation? 
Can you test it with English? 
We don't deal normally with translations here, and French translation is not provided here. I'll ask Cesag to look into it....

**Comment by cesag** [comment]
I tested with french version and english version.
In french version, we don't have the pop-up calendar and if we want to modify the date, we have to enter the date like this : dd-mm-yyyy. If we enter the date like this : dd/mm/yyyy or yyyy/mm/dd, the date is displayed with one day less.
When I test with Xoops and Xoopspoll in english, everything is working.

**Comment by cesag** [comment]
Apparently, the expiration date you enter into the field, should be written like this: n/j/yyyy

and I don't know why...
